// Automatisch generiert — Dashboard-Bilderverwaltung (worker/src/site-gen.js)
const IMAGES = {
  food: [
    "images/tiles/food/51-schokokirsche.jpg",
    "images/tiles/food/52-kaffee-milch.jpg",
    "images/tiles/food/60-dimple-drink-art.jpg",
    "images/tiles/food/63-fine-dining.jpg",
    "images/tiles/food/65-liptonice.jpg",
    "images/tiles/food/66-mezzomix.jpg",
    "images/tiles/food/68-nutella-fussball.jpg",
    "images/tiles/food/70-sarotti-likoer-splash.jpg",
    "images/tiles/food/71-schokolikoer.jpg",
    "images/tiles/food/73-tomaten.jpg",
    "images/tiles/food/50-pflaume-feige.jpg",
    "images/tiles/food/53-orangenmarmelade.jpg",
    "images/tiles/food/54-creme-de-balsamico.jpg",
    "images/tiles/food/55-drinks-exotisch.jpg",
    "images/tiles/food/56-lime-coffee.jpg",
    "images/tiles/food/57-bebivita-schoko.jpg",
    "images/tiles/food/58-birne-apfel.jpg",
    "images/tiles/food/59-caffreddo.jpg",
    "images/tiles/food/61-eiscafe.jpg",
    "images/tiles/food/62-fertiggerichte.jpg",
    "images/tiles/food/64-halloren-waldfrucht.jpg",
    "images/tiles/food/67-milchkaffee.jpg",
    "images/tiles/food/69-oranges.jpg",
    "images/tiles/food/72-tegut-muesliriegel.jpg",
    "images/tiles/food/74-valbrie.jpg",
  ],
  transport: [
    "images/tiles/transport/50-red-racer.jpg",
    "images/tiles/transport/52-pink-cadillac.jpg",
    "images/tiles/transport/53-db-ice.jpg",
    "images/tiles/transport/54-dreamcar.jpg",
    "images/tiles/transport/55-ferrari-f-50.jpg",
    "images/tiles/transport/56-easyriders.jpg",
    "images/tiles/transport/61-motorace.jpg",
    "images/tiles/transport/63-easifixk.jpg",
    "images/tiles/transport/66-vedder-bootsausstattung.jpg",
    "images/tiles/transport/51-alvis-roadster.jpg",
    "images/tiles/transport/58-alfa-romeo.jpg",
    "images/tiles/transport/59-monster-trucks.jpg",
    "images/tiles/transport/60-moto-cross.jpg",
    "images/tiles/transport/62-verkehrswege.jpg",
    "images/tiles/transport/64-wassertest.jpg",
    "images/tiles/transport/65-starck-wc.jpg",
    "images/tiles/transport/67-vedder-systemtisch.jpg",
    "images/tiles/transport/68-buffer-anlage.jpg",
    "images/tiles/transport/69-manz-robot.jpg",
  ],
  landscape: [
    "images/tiles/landscape/50-airstream.jpg",
    "images/tiles/landscape/51-almette.jpg",
    "images/tiles/landscape/52-alte-oper-plakat.jpg",
    "images/tiles/landscape/53-cant-stop.jpg",
    "images/tiles/landscape/54-cutty-sark.jpg",
    "images/tiles/landscape/57-faszination-fussball.jpg",
    "images/tiles/landscape/59-gas-station.jpg",
    "images/tiles/landscape/64-maggi-toscana.jpg",
    "images/tiles/landscape/66-pharaonengrab.jpg",
    "images/tiles/landscape/68-segelregatta.jpg",
    "images/tiles/landscape/71-underwater.jpg",
    "images/tiles/landscape/72-vodafone-zuhause.jpg",
    "images/tiles/landscape/74-worldgate.jpg",
    "images/tiles/landscape/55-delphine-mit-truhe.jpg",
    "images/tiles/landscape/56-energie-landschaften.jpg",
    "images/tiles/landscape/58-ferrero-pasticceria.jpg",
    "images/tiles/landscape/60-haus-innen-neu.jpg",
    "images/tiles/landscape/61-fussball-kulinarisch.jpg",
    "images/tiles/landscape/62-hollandrad.jpg",
    "images/tiles/landscape/63-kuba.jpg",
    "images/tiles/landscape/65-maerchenschloss.jpg",
    "images/tiles/landscape/67-plantage.jpg",
    "images/tiles/landscape/69-sonnensystem.jpg",
    "images/tiles/landscape/70-suedsee.jpg",
    "images/tiles/landscape/73-weideglueck.jpg",
  ],
  people: [
    "images/tiles/people/50-bosch-halogen.jpg",
    "images/tiles/people/52-konditor-bildmarke.jpg",
    "images/tiles/people/53-lippenstift.jpg",
    "images/tiles/people/54-hula-hoop-girl.jpg",
    "images/tiles/people/55-foetus.jpg",
    "images/tiles/people/57-kleenex.jpg",
    "images/tiles/people/59-rene-garraud.jpg",
    "images/tiles/people/62-joker.jpg",
    "images/tiles/people/64-schweinischer-engel.jpg",
    "images/tiles/people/66-hr3-hoerminator.jpg",
    "images/tiles/people/68-drachentoeter.jpg",
    "images/tiles/people/51-cavallino-rampante.jpg",
    "images/tiles/people/56-kaesemeister.jpg",
    "images/tiles/people/58-lollypop-mann.jpg",
    "images/tiles/people/60-weihnachtsschokolade.jpg",
    "images/tiles/people/61-maggi-diavolo.jpg",
    "images/tiles/people/63-comic-motive.jpg",
    "images/tiles/people/65-wassermusik.jpg",
    "images/tiles/people/67-tyrannosaurus-rex.jpg",
    "images/tiles/people/69-hunde.jpg",
  ],
  items: [
    "images/tiles/items/50-bad-liebenzeller.jpg",
    "images/tiles/items/54-cutimed-produkte.jpg",
    "images/tiles/items/56-edelstahl.jpg",
    "images/tiles/items/57-glaskopf.jpg",
    "images/tiles/items/59-honigmilch.jpg",
    "images/tiles/items/60-maggi-ofen-filet.jpg",
    "images/tiles/items/61-makebreak.jpg",
    "images/tiles/items/62-oelkanister.jpg",
    "images/tiles/items/63-partitur.jpg",
    "images/tiles/items/65-rabanus-bier.jpg",
    "images/tiles/items/69-ventslots.jpg",
    "images/tiles/items/70-wasserfilter.jpg",
    "images/tiles/items/71-wasserwerke.jpg",
    "images/tiles/items/74-wick-salbei-pack.jpg",
    "images/tiles/items/51-barrier-pflaster.jpg",
    "images/tiles/items/52-blattameise.jpg",
    "images/tiles/items/53-crystal.jpg",
    "images/tiles/items/55-easyfix-crinx.jpg",
    "images/tiles/items/58-golden-shoe.jpg",
    "images/tiles/items/59-molekuele2-1.jpg",
    "images/tiles/items/64-pencil-knot.jpg",
    "images/tiles/items/66-schneiddeckel.jpg",
    "images/tiles/items/67-telefonieren-und-surfen.jpg",
    "images/tiles/items/68-edelstahl-ultra.jpg",
    "images/tiles/items/72-weihnachtskarte-frankfurt.jpg",
    "images/tiles/items/73-weihnachtskarte-lb.jpg",
    "images/tiles/items/74-zahnbehandlung.jpg",
  ],
  poster: [
    "images/tiles/poster/51-akrinor-oral.jpg",
    "images/tiles/poster/52-alte-oper.jpg",
    "images/tiles/poster/56-hakle-london.jpg",
    "images/tiles/poster/57-harry-keaton-poster.jpg",
    "images/tiles/poster/58-scorpions-cover.jpg",
    "images/tiles/poster/61-kinder-advent.jpg",
    "images/tiles/poster/64-neuselters.jpg",
    "images/tiles/poster/66-oral-b.jpg",
    "images/tiles/poster/70-schwanensee.jpg",
    "images/tiles/poster/71-shell-formel1.jpg",
    "images/tiles/poster/73-wurlitzer.jpg",
    "images/tiles/poster/74-pioneer-hifi.jpg",
    "images/tiles/poster/50-adventskalender.jpg",
    "images/tiles/poster/53-batida-plakat.jpg",
    "images/tiles/poster/54-douwe-egberts.jpg",
    "images/tiles/poster/55-floradix.jpg",
    "images/tiles/poster/58-huegli-titel.jpg",
    "images/tiles/poster/59-kinder-snoopy.jpg",
    "images/tiles/poster/60-kleenex.jpg",
    "images/tiles/poster/62-marlboro-moskau.jpg",
    "images/tiles/poster/63-shell-lenkdrachen.jpg",
    "images/tiles/poster/65-new-york.jpg",
    "images/tiles/poster/67-picanto-poster.jpg",
    "images/tiles/poster/68-geniessen.jpg",
    "images/tiles/poster/69-meckmotors-logo.jpg",
    "images/tiles/poster/72-shell-tankwart.jpg",
  ],
  pharma: [
    "images/tiles/pharma/51-akrinor2.jpg",
    "images/tiles/pharma/53-alzheimer.jpg",
    "images/tiles/pharma/55-blutgerinnung.jpg",
    "images/tiles/pharma/56-capillary-leak.jpg",
    "images/tiles/pharma/58-easyfix-crinx.jpg",
    "images/tiles/pharma/60-foetus.jpg",
    "images/tiles/pharma/61-hirnblutung.jpg",
    "images/tiles/pharma/64-molekuel.jpg",
    "images/tiles/pharma/65-mundspuelung.jpg",
    "images/tiles/pharma/66-sklerose.jpg",
    "images/tiles/pharma/50-akrinor1.jpg",
    "images/tiles/pharma/52-akrinor3.jpg",
    "images/tiles/pharma/54-biofilm.jpg",
    "images/tiles/pharma/57-coverplast.jpg",
    "images/tiles/pharma/59-elastoplast.jpg",
    "images/tiles/pharma/62-lymhsystem.jpg",
    "images/tiles/pharma/63-lymphsystem-legs.jpg",
    "images/tiles/pharma/67-thrombus.jpg",
    "images/tiles/pharma/68-tumor-grenzregion.jpg",
    "images/tiles/pharma/69-uteral-bleeding.jpg",
  ],
  logos: [
    "images/tiles/logos/50-ali-baba.jpg",
    "images/tiles/logos/54-bizzl-logo.jpg",
    "images/tiles/logos/55-celtica.jpg",
    "images/tiles/logos/59-indigo.jpg",
    "images/tiles/logos/61-leaf-cup.jpg",
    "images/tiles/logos/63-moguntia.jpg",
    "images/tiles/logos/66-neon-sign.jpg",
    "images/tiles/logos/67-paper-creation.jpg",
    "images/tiles/logos/69-sciencex.jpg",
    "images/tiles/logos/72-xxl.jpg",
    "images/tiles/logos/73-xylit.jpg",
    "images/tiles/logos/51-art-of-fantasy.jpg",
    "images/tiles/logos/52-baders.jpg",
    "images/tiles/logos/53-bidcar24.jpg",
    "images/tiles/logos/56-css-logo.jpg",
    "images/tiles/logos/56-meckmotors-vintage.jpg",
    "images/tiles/logos/57-frankfurt-film.jpg",
    "images/tiles/logos/58-grafilino.jpg",
    "images/tiles/logos/60-joy-logo.jpg",
    "images/tiles/logos/62-mexica.jpg",
    "images/tiles/logos/64-name-der-rose.jpg",
    "images/tiles/logos/65-nebelhorn-logo.jpg",
    "images/tiles/logos/68-bake-create.jpg",
    "images/tiles/logos/68-saucenmedallie.jpg",
    "images/tiles/logos/70-spardoch.jpg",
    "images/tiles/logos/71-timesquare.jpg",
    "images/tiles/logos/74-zeitperlen.jpg",
  ],
  packaging: [
    "images/tiles/packaging/50-big-kini.jpg",
    "images/tiles/packaging/51-bluff.jpg",
    "images/tiles/packaging/52-buddel-company.jpg",
    "images/tiles/packaging/57-himbeergeist.jpg",
    "images/tiles/packaging/62-leaf-cup.jpg",
    "images/tiles/packaging/66-mon-cheri-ei.jpg",
    "images/tiles/packaging/67-mon-cheri-fruehling.jpg",
    "images/tiles/packaging/68-multivitamin.jpg",
    "images/tiles/packaging/69-piraten.jpg",
    "images/tiles/packaging/71-royal-casino.jpg",
    "images/tiles/packaging/72-teastar-display.jpg",
    "images/tiles/packaging/73-tops.jpg",
    "images/tiles/packaging/74-zaubershow.jpg",
    "images/tiles/packaging/53-display-teastar.jpg",
    "images/tiles/packaging/54-energietaler.jpg",
    "images/tiles/packaging/55-froeschle-tiernahrung.jpg",
    "images/tiles/packaging/56-gedaechtnistee.jpg",
    "images/tiles/packaging/58-huegli-gourmet.jpg",
    "images/tiles/packaging/59-joy-dosen.jpg",
    "images/tiles/packaging/60-joy-display.jpg",
    "images/tiles/packaging/61-konfituere.jpg",
    "images/tiles/packaging/63-lemon.jpg",
    "images/tiles/packaging/64-lindt-geschenkpackung.jpg",
    "images/tiles/packaging/65-maggi-benedict.jpg",
    "images/tiles/packaging/70-premium-tea.jpg",
  ],
};
const FEATURED = [
  "images/tiles/food/51-schokokirsche.jpg",
  "images/tiles/food/52-kaffee-milch.jpg",
  "images/tiles/food/60-dimple-drink-art.jpg",
  "images/tiles/food/63-fine-dining.jpg",
  "images/tiles/food/65-liptonice.jpg",
  "images/tiles/food/66-mezzomix.jpg",
  "images/tiles/food/68-nutella-fussball.jpg",
  "images/tiles/food/70-sarotti-likoer-splash.jpg",
  "images/tiles/food/71-schokolikoer.jpg",
  "images/tiles/food/73-tomaten.jpg",
  "images/tiles/transport/50-red-racer.jpg",
  "images/tiles/transport/52-pink-cadillac.jpg",
  "images/tiles/transport/53-db-ice.jpg",
  "images/tiles/transport/54-dreamcar.jpg",
  "images/tiles/transport/55-ferrari-f-50.jpg",
  "images/tiles/transport/56-easyriders.jpg",
  "images/tiles/transport/61-motorace.jpg",
  "images/tiles/transport/63-easifixk.jpg",
  "images/tiles/transport/66-vedder-bootsausstattung.jpg",
  "images/tiles/landscape/50-airstream.jpg",
  "images/tiles/landscape/51-almette.jpg",
  "images/tiles/landscape/52-alte-oper-plakat.jpg",
  "images/tiles/landscape/53-cant-stop.jpg",
  "images/tiles/landscape/54-cutty-sark.jpg",
  "images/tiles/landscape/57-faszination-fussball.jpg",
  "images/tiles/landscape/59-gas-station.jpg",
  "images/tiles/landscape/64-maggi-toscana.jpg",
  "images/tiles/landscape/66-pharaonengrab.jpg",
  "images/tiles/landscape/68-segelregatta.jpg",
  "images/tiles/landscape/71-underwater.jpg",
  "images/tiles/landscape/72-vodafone-zuhause.jpg",
  "images/tiles/landscape/74-worldgate.jpg",
  "images/tiles/people/50-bosch-halogen.jpg",
  "images/tiles/people/52-konditor-bildmarke.jpg",
  "images/tiles/people/53-lippenstift.jpg",
  "images/tiles/people/54-hula-hoop-girl.jpg",
  "images/tiles/people/55-foetus.jpg",
  "images/tiles/people/57-kleenex.jpg",
  "images/tiles/people/59-rene-garraud.jpg",
  "images/tiles/people/62-joker.jpg",
  "images/tiles/people/64-schweinischer-engel.jpg",
  "images/tiles/people/66-hr3-hoerminator.jpg",
  "images/tiles/people/68-drachentoeter.jpg",
  "images/tiles/items/50-bad-liebenzeller.jpg",
  "images/tiles/items/54-cutimed-produkte.jpg",
  "images/tiles/items/56-edelstahl.jpg",
  "images/tiles/items/57-glaskopf.jpg",
  "images/tiles/items/59-honigmilch.jpg",
  "images/tiles/items/60-maggi-ofen-filet.jpg",
  "images/tiles/items/61-makebreak.jpg",
  "images/tiles/items/62-oelkanister.jpg",
  "images/tiles/items/63-partitur.jpg",
  "images/tiles/items/65-rabanus-bier.jpg",
  "images/tiles/items/69-ventslots.jpg",
  "images/tiles/items/70-wasserfilter.jpg",
  "images/tiles/items/71-wasserwerke.jpg",
  "images/tiles/items/74-wick-salbei-pack.jpg",
  "images/tiles/poster/51-akrinor-oral.jpg",
  "images/tiles/poster/52-alte-oper.jpg",
  "images/tiles/poster/56-hakle-london.jpg",
  "images/tiles/poster/57-harry-keaton-poster.jpg",
  "images/tiles/poster/58-scorpions-cover.jpg",
  "images/tiles/poster/61-kinder-advent.jpg",
  "images/tiles/poster/64-neuselters.jpg",
  "images/tiles/poster/66-oral-b.jpg",
  "images/tiles/poster/70-schwanensee.jpg",
  "images/tiles/poster/71-shell-formel1.jpg",
  "images/tiles/poster/73-wurlitzer.jpg",
  "images/tiles/poster/74-pioneer-hifi.jpg",
  "images/tiles/pharma/51-akrinor2.jpg",
  "images/tiles/pharma/53-alzheimer.jpg",
  "images/tiles/pharma/55-blutgerinnung.jpg",
  "images/tiles/pharma/56-capillary-leak.jpg",
  "images/tiles/pharma/58-easyfix-crinx.jpg",
  "images/tiles/pharma/60-foetus.jpg",
  "images/tiles/pharma/61-hirnblutung.jpg",
  "images/tiles/pharma/64-molekuel.jpg",
  "images/tiles/pharma/65-mundspuelung.jpg",
  "images/tiles/pharma/66-sklerose.jpg",
  "images/tiles/logos/50-ali-baba.jpg",
  "images/tiles/logos/54-bizzl-logo.jpg",
  "images/tiles/logos/55-celtica.jpg",
  "images/tiles/logos/59-indigo.jpg",
  "images/tiles/logos/61-leaf-cup.jpg",
  "images/tiles/logos/63-moguntia.jpg",
  "images/tiles/logos/66-neon-sign.jpg",
  "images/tiles/logos/67-paper-creation.jpg",
  "images/tiles/logos/69-sciencex.jpg",
  "images/tiles/logos/72-xxl.jpg",
  "images/tiles/logos/73-xylit.jpg",
  "images/tiles/packaging/50-big-kini.jpg",
  "images/tiles/packaging/51-bluff.jpg",
  "images/tiles/packaging/52-buddel-company.jpg",
  "images/tiles/packaging/57-himbeergeist.jpg",
  "images/tiles/packaging/62-leaf-cup.jpg",
  "images/tiles/packaging/66-mon-cheri-ei.jpg",
  "images/tiles/packaging/67-mon-cheri-fruehling.jpg",
  "images/tiles/packaging/68-multivitamin.jpg",
  "images/tiles/packaging/69-piraten.jpg",
  "images/tiles/packaging/71-royal-casino.jpg",
  "images/tiles/packaging/72-teastar-display.jpg",
  "images/tiles/packaging/73-tops.jpg",
  "images/tiles/packaging/74-zaubershow.jpg",
];
const TITLES = {
  "images/tiles/food/51-schokokirsche.jpg": {"de":"Schokokirsche","en":"Chocolate Cherry","es":"Cereza de chocolate","fr":"Cerise au chocolat","it":"Ciliegia al cioccolato"},
  "images/tiles/food/52-kaffee-milch.jpg": {"de":"Kaffee Milch","en":"Coffee Milk","es":"Café con leche","fr":"Café au lait","it":"Caffè e latte"},
  "images/tiles/food/60-dimple-drink-art.jpg": {"de":"Dimple Drink Art","en":"Dimple Drink Art","es":"Dimple arte de la bebida","fr":"Dimple art du cocktail","it":"Dimple arte del drink"},
  "images/tiles/food/63-fine-dining.jpg": {"de":"Fine Dining","en":"Fine Dining","es":"Alta cocina","fr":"Haute gastronomie","it":"Alta cucina"},
  "images/tiles/food/65-liptonice.jpg": {"de":"Liptonice","en":"Liptonice","es":"Liptonice","fr":"Liptonice","it":"Liptonice"},
  "images/tiles/food/66-mezzomix.jpg": {"de":"Mezzomix","en":"Mezzomix","es":"Mezzomix","fr":"Mezzomix","it":"Mezzomix"},
  "images/tiles/food/68-nutella-fussball.jpg": {"de":"Plakat für Nutella Werbung im Fussball Kontext","en":"Poster for Nutella Advertising in Football Context","es":"Nutella fútbol","fr":"Nutella football","it":"Nutella calcio"},
  "images/tiles/food/70-sarotti-likoer-splash.jpg": {"de":"Sarotti Likör Splash","en":"Sarotti Liqueur Splash","es":"Sarotti salpicadura de licor","fr":"Sarotti éclaboussure de liqueur","it":"Sarotti schizzo di liquore"},
  "images/tiles/food/71-schokolikoer.jpg": {"de":"Schokolikör","en":"Chocolate Liqueur","es":"Licor de chocolate","fr":"Liqueur au chocolat","it":"Liquore al cioccolato"},
  "images/tiles/food/73-tomaten.jpg": {"de":"Tomaten","en":"Tomatoes","es":"Tomates","fr":"Tomates","it":"Pomodori"},
  "images/tiles/food/50-pflaume-feige.jpg": {"de":"Pflaume Feige","en":"Plum Fig","es":"Ciruela e higo","fr":"Prune et figue","it":"Prugna e fico"},
  "images/tiles/food/53-orangenmarmelade.jpg": {"de":"Orangenmarmelade","en":"Orange Marmalade","es":"Mermelada de naranja","fr":"Marmelade d'orange","it":"Marmellata d'arancia"},
  "images/tiles/food/54-creme-de-balsamico.jpg": {"de":"Creme De Balsamico","en":"Balsamic Cream","es":"Crema de balsámico","fr":"Crème de balsamique","it":"Crema di balsamico"},
  "images/tiles/food/55-drinks-exotisch.jpg": {"de":"Drinks Exotisch","en":"Exotic Drinks","es":"Bebidas exóticas","fr":"Boissons exotiques","it":"Bevande esotiche"},
  "images/tiles/food/56-lime-coffee.jpg": {"de":"Lime Coffee","en":"Lime Coffee","es":"Café con lima","fr":"Café au citron vert","it":"Caffè al lime"},
  "images/tiles/food/57-bebivita-schoko.jpg": {"de":"Bebivita Schoko","en":"Bebivita Chocolate","es":"Bebivita chocolate","fr":"Bebivita chocolat","it":"Bebivita cioccolato"},
  "images/tiles/food/58-birne-apfel.jpg": {"de":"Birne Apfel","en":"Pear Apple","es":"Pera y manzana","fr":"Poire et pomme","it":"Pera e mela"},
  "images/tiles/food/59-caffreddo.jpg": {"de":"Caffreddo","en":"Caffreddo","es":"Caffreddo","fr":"Caffreddo","it":"Caffreddo"},
  "images/tiles/food/61-eiscafe.jpg": {"de":"Eiscafe","en":"Ice Cream Parlour","es":"Heladería","fr":"Glacier","it":"Gelateria"},
  "images/tiles/food/62-fertiggerichte.jpg": {"de":"Fertiggerichte","en":"Ready Meals","es":"Platos preparados","fr":"Plats cuisinés","it":"Piatti pronti"},
  "images/tiles/food/64-halloren-waldfrucht.jpg": {"de":"Halloren Waldfrucht","en":"Halloren Forest Fruit","es":"Halloren frutas del bosque","fr":"Halloren fruits des bois","it":"Halloren frutti di bosco"},
  "images/tiles/food/67-milchkaffee.jpg": {"de":"Milchkaffee","en":"Café au Lait","es":"Café con leche","fr":"Café au lait","it":"Caffellatte"},
  "images/tiles/food/69-oranges.jpg": {"de":"Oranges","en":"Oranges","es":"Naranjas","fr":"Oranges","it":"Arance"},
  "images/tiles/food/72-tegut-muesliriegel.jpg": {"de":"Tegut Müsliriegel","en":"tegut Muesli Bar","es":"tegut barrita de muesli","fr":"tegut barre de muesli","it":"tegut barretta di muesli"},
  "images/tiles/food/74-valbrie.jpg": {"de":"Valbrie","en":"Valbrie","es":"Valbrie","fr":"Valbrie","it":"Valbrie"},
  "images/tiles/transport/50-red-racer.jpg": {"de":"Red Racer","en":"Red Racer","es":"Corredor rojo","fr":"Bolide rouge","it":"Bolide rosso"},
  "images/tiles/transport/52-pink-cadillac.jpg": {"de":"Pink Cadillac","en":"Pink Cadillac","es":"Pink Cadillac","fr":"Pink Cadillac","it":"Pink Cadillac"},
  "images/tiles/transport/53-db-ice.jpg": {"de":"Db Ice","en":"DB Ice","es":"DB Ice","fr":"DB Ice","it":"DB Ice"},
  "images/tiles/transport/54-dreamcar.jpg": {"de":"Dreamcar","en":"Dream Car","es":"Coche de ensueño","fr":"Voiture de rêve","it":"Auto dei sogni"},
  "images/tiles/transport/55-ferrari-f-50.jpg": {"de":"Ferrari F 50","en":"Ferrari F 50","es":"Ferrari F 50","fr":"Ferrari F 50","it":"Ferrari F 50"},
  "images/tiles/transport/56-easyriders.jpg": {"de":"Easyriders","en":"Easyriders","es":"Easyriders","fr":"Easyriders","it":"Easyriders"},
  "images/tiles/transport/61-motorace.jpg": {"de":"Motorace","en":"Motorace","es":"Motorace","fr":"Motorace","it":"Motorace"},
  "images/tiles/transport/63-easifixk.jpg": {"de":"Easifixk","en":"Easifixk","es":"Easifixk","fr":"Easifixk","it":"Easifixk"},
  "images/tiles/transport/66-vedder-bootsausstattung.jpg": {"de":"Vedder Bootsausstattung","en":"Vedder Boat Fittings","es":"Vedder equipamiento náutico","fr":"Vedder équipement de bateau","it":"Vedder allestimenti nautici"},
  "images/tiles/transport/51-alvis-roadster.jpg": {"de":"Alvis Roadster","en":"Alvis Roadster","es":"Alvis Roadster","fr":"Alvis Roadster","it":"Alvis Roadster"},
  "images/tiles/transport/58-alfa-romeo.jpg": {"de":"Alfa Romeo","en":"Alfa Romeo","es":"Alfa Romeo","fr":"Alfa Romeo","it":"Alfa Romeo"},
  "images/tiles/transport/59-monster-trucks.jpg": {"de":"Monster Trucks","en":"Monster Trucks","es":"Monster trucks","fr":"Monster trucks","it":"Monster truck"},
  "images/tiles/transport/60-moto-cross.jpg": {"de":"Moto Croß","en":"Motocross","es":"Motocross","fr":"Motocross","it":"Motocross"},
  "images/tiles/transport/62-verkehrswege.jpg": {"de":"Verkehrswege","en":"Transport Routes","es":"Vías de transporte","fr":"Voies de circulation","it":"Vie di comunicazione"},
  "images/tiles/transport/64-wassertest.jpg": {"de":"Wassertest","en":"Water Test","es":"Prueba del agua","fr":"Test de l'eau","it":"Test dell'acqua"},
  "images/tiles/transport/65-starck-wc.jpg": {"de":"Starck Wc","en":"Starck WC","es":"Starck WC","fr":"WC Starck","it":"WC Starck"},
  "images/tiles/transport/67-vedder-systemtisch.jpg": {"de":"Vedder Systemtisch","en":"Vedder System Table","es":"Vedder mesa modular","fr":"Vedder table modulaire","it":"Vedder tavolo modulare"},
  "images/tiles/transport/68-buffer-anlage.jpg": {"de":"Buffer Anlage","en":"Buffer Plant","es":"Instalación tampón","fr":"Installation tampon","it":"Impianto tampone"},
  "images/tiles/transport/69-manz-robot.jpg": {"de":"Manz Robot","en":"Manz Robot","es":"Manz robot","fr":"Manz robot","it":"Manz robot"},
  "images/tiles/landscape/50-airstream.jpg": {"de":"Airstream","en":"Airstream","es":"Airstream","fr":"Airstream","it":"Airstream"},
  "images/tiles/landscape/51-almette.jpg": {"de":"Almette","en":"Almette","es":"Almette","fr":"Almette","it":"Almette"},
  "images/tiles/landscape/52-alte-oper-plakat.jpg": {"de":"Alte Oper Plakat","en":"Alte Oper Poster","es":"Cartel Alte Oper","fr":"Affiche Alte Oper","it":"Manifesto Alte Oper"},
  "images/tiles/landscape/53-cant-stop.jpg": {"de":"Cant Stop","en":"Can't Stop","es":"Can't Stop","fr":"Can't Stop","it":"Can't Stop"},
  "images/tiles/landscape/54-cutty-sark.jpg": {"de":"Cutty Sark","en":"Cutty Sark","es":"Cutty Sark","fr":"Cutty Sark","it":"Cutty Sark"},
  "images/tiles/landscape/57-faszination-fussball.jpg": {"de":"Faszination Fussball","en":"Fascination Football","es":"Fascinación por el fútbol","fr":"Fascination du football","it":"Fascino del calcio"},
  "images/tiles/landscape/59-gas-station.jpg": {"de":"Gas Station","en":"Gas Station","es":"Gasolinera","fr":"Station-service","it":"Stazione di servizio"},
  "images/tiles/landscape/64-maggi-toscana.jpg": {"de":"Maggi Toscana","en":"Maggi Toscana","es":"Maggi Toscana","fr":"Maggi Toscana","it":"Maggi Toscana"},
  "images/tiles/landscape/66-pharaonengrab.jpg": {"de":"Pharaonengrab","en":"Pharaoh's Tomb","es":"Tumba del faraón","fr":"Tombeau du pharaon","it":"Tomba del faraone"},
  "images/tiles/landscape/68-segelregatta.jpg": {"de":"Segelregatta","en":"Sailing Regatta","es":"Regata de vela","fr":"Régate à la voile","it":"Regata velica"},
  "images/tiles/landscape/71-underwater.jpg": {"de":"Underwater","en":"Underwater","es":"Bajo el agua","fr":"Sous l'eau","it":"Sott'acqua"},
  "images/tiles/landscape/72-vodafone-zuhause.jpg": {"de":"Vodafone Zuhause","en":"Vodafone Home","es":"Vodafone hogar","fr":"Vodafone à la maison","it":"Vodafone casa"},
  "images/tiles/landscape/74-worldgate.jpg": {"de":"Worldgate","en":"Worldgate","es":"Worldgate","fr":"Worldgate","it":"Worldgate"},
  "images/tiles/landscape/55-delphine-mit-truhe.jpg": {"de":"Delphine Mit Truhe","en":"Dolphins with Treasure Chest","es":"Delfines con cofre","fr":"Dauphins avec coffre","it":"Delfini con forziere"},
  "images/tiles/landscape/56-energie-landschaften.jpg": {"de":"Energie Landschaften","en":"Energy Landscapes","es":"Paisajes energéticos","fr":"Paysages énergétiques","it":"Paesaggi dell'energia"},
  "images/tiles/landscape/58-ferrero-pasticceria.jpg": {"de":"Ferrero Pasticceria","en":"Ferrero Pasticceria","es":"Ferrero Pasticceria","fr":"Ferrero Pasticceria","it":"Ferrero Pasticceria"},
  "images/tiles/landscape/60-haus-innen-neu.jpg": {"de":"Haus Innen Neu","en":"House Interior","es":"Interior de la casa","fr":"Intérieur de maison","it":"Interno di casa"},
  "images/tiles/landscape/61-fussball-kulinarisch.jpg": {"de":"Fussball Kulinarisch","en":"Football in the Kitchen","es":"Fútbol culinario","fr":"Football culinaire","it":"Calcio in cucina"},
  "images/tiles/landscape/62-hollandrad.jpg": {"de":"Hollandrad","en":"Dutch Bicycle","es":"Bicicleta holandesa","fr":"Vélo hollandais","it":"Bicicletta olandese"},
  "images/tiles/landscape/63-kuba.jpg": {"de":"Kuba","en":"Cuba","es":"Cuba","fr":"Cuba","it":"Cuba"},
  "images/tiles/landscape/65-maerchenschloss.jpg": {"de":"Märchenschloß","en":"Fairytale Castle","es":"Castillo de cuento","fr":"Château de conte de fées","it":"Castello delle fiabe"},
  "images/tiles/landscape/67-plantage.jpg": {"de":"Plantage","en":"Plantation","es":"Plantación","fr":"Plantation","it":"Piantagione"},
  "images/tiles/landscape/69-sonnensystem.jpg": {"de":"Sonnensystem","en":"Solar System","es":"Sistema solar","fr":"Système solaire","it":"Sistema solare"},
  "images/tiles/landscape/70-suedsee.jpg": {"de":"Südsee","en":"South Seas","es":"Mares del Sur","fr":"Mers du Sud","it":"Mari del Sud"},
  "images/tiles/landscape/73-weideglueck.jpg": {"de":"Weideglück","en":"Weideglück","es":"Weideglück","fr":"Weideglück","it":"Weideglück"},
  "images/tiles/people/50-bosch-halogen.jpg": {"de":"Bosch Halogen","en":"Bosch Halogen","es":"Bosch Halógeno","fr":"Bosch Halogène","it":"Bosch Alogena"},
  "images/tiles/people/52-konditor-bildmarke.jpg": {"de":"Konditor Bildmarke","en":"Confectioner Pictorial Mark","es":"Marca figurativa de pastelería","fr":"Marque figurative de pâtisserie","it":"Marchio figurativo di pasticceria"},
  "images/tiles/people/53-lippenstift.jpg": {"de":"Lippenstift","en":"Lipstick","es":"Pintalabios","fr":"Rouge à lèvres","it":"Rossetto"},
  "images/tiles/people/54-hula-hoop-girl.jpg": {"de":"Hula Hoop Girl","en":"Hula Hoop Girl","es":"Chica del hula hoop","fr":"Fille au hula hoop","it":"Ragazza con l'hula hoop"},
  "images/tiles/people/55-foetus.jpg": {"de":"Fötus","en":"Foetus","es":"Feto","fr":"Fœtus","it":"Feto"},
  "images/tiles/people/57-kleenex.jpg": {"de":"Kleenex","en":"Kleenex","es":"Kleenex","fr":"Kleenex","it":"Kleenex"},
  "images/tiles/people/59-rene-garraud.jpg": {"de":"Rene Garraud","en":"Rene Garraud","es":"Rene Garraud","fr":"Rene Garraud","it":"Rene Garraud"},
  "images/tiles/people/62-joker.jpg": {"de":"Joker","en":"Joker","es":"Joker","fr":"Joker","it":"Joker"},
  "images/tiles/people/64-schweinischer-engel.jpg": {"de":"Schweinischer Engel","en":"Swinish Angel","es":"Ángel porcino","fr":"Ange cochon","it":"Angelo porcello"},
  "images/tiles/people/66-hr3-hoerminator.jpg": {"de":"Hr3 Hörminator","en":"hr3 Hörminator","es":"hr3 Hörminator","fr":"hr3 Hörminator","it":"hr3 Hörminator"},
  "images/tiles/people/68-drachentoeter.jpg": {"de":"Drachentöter","en":"Dragon Slayer","es":"Matadragones","fr":"Tueur de dragon","it":"Ammazzadraghi"},
  "images/tiles/people/51-cavallino-rampante.jpg": {"de":"Cavallino Rampante","en":"Cavallino Rampante","es":"Cavallino Rampante","fr":"Cavallino Rampante","it":"Cavallino Rampante"},
  "images/tiles/people/56-kaesemeister.jpg": {"de":"Käsemeister","en":"Cheese Master","es":"Maestro quesero","fr":"Maître fromager","it":"Maestro casaro"},
  "images/tiles/people/58-lollypop-mann.jpg": {"de":"Lollypop Mann","en":"Lollypop Man","es":"Hombre piruleta","fr":"Homme sucette","it":"Uomo lecca-lecca"},
  "images/tiles/people/60-weihnachtsschokolade.jpg": {"de":"Weihnachtsschokolade","en":"Christmas Chocolate","es":"Chocolate navideño","fr":"Chocolat de Noël","it":"Cioccolato di Natale"},
  "images/tiles/people/61-maggi-diavolo.jpg": {"de":"Maggi Diavolo","en":"Maggi Diavolo","es":"Maggi Diavolo","fr":"Maggi Diavolo","it":"Maggi Diavolo"},
  "images/tiles/people/63-comic-motive.jpg": {"de":"Comic Motive","en":"Comic Motifs","es":"Motivos de cómic","fr":"Motifs de bande dessinée","it":"Motivi a fumetti"},
  "images/tiles/people/65-wassermusik.jpg": {"de":"Wassermusik","en":"Water Music","es":"Música acuática","fr":"Musique aquatique","it":"Musica sull'acqua"},
  "images/tiles/people/67-tyrannosaurus-rex.jpg": {"de":"Tyrannosaurus Rex","en":"Tyrannosaurus Rex","es":"Tyrannosaurus Rex","fr":"Tyrannosaurus Rex","it":"Tyrannosaurus Rex"},
  "images/tiles/people/69-hunde.jpg": {"de":"Hunde","en":"Dogs","es":"Perros","fr":"Chiens","it":"Cani"},
  "images/tiles/items/50-bad-liebenzeller.jpg": {"de":"Bad Liebenzeller","en":"Bad Liebenzeller","es":"Bad Liebenzeller","fr":"Bad Liebenzeller","it":"Bad Liebenzeller"},
  "images/tiles/items/54-cutimed-produkte.jpg": {"de":"Cutimed Produkte","en":"Cutimed Products","es":"Productos Cutimed","fr":"Produits Cutimed","it":"Prodotti Cutimed"},
  "images/tiles/items/56-edelstahl.jpg": {"de":"Edelstahl","en":"Stainless Steel","es":"Acero inoxidable","fr":"Acier inoxydable","it":"Acciaio inox"},
  "images/tiles/items/57-glaskopf.jpg": {"de":"Glaskopf","en":"Glass Head","es":"Cabeza de vidrio","fr":"Tête de verre","it":"Testa di vetro"},
  "images/tiles/items/59-honigmilch.jpg": {"de":"Honigmilch","en":"Honey Milk","es":"Leche con miel","fr":"Lait au miel","it":"Latte al miele"},
  "images/tiles/items/60-maggi-ofen-filet.jpg": {"de":"Maggi Ofen Filet","en":"Maggi Oven Fillet","es":"Maggi filete al horno","fr":"Maggi filet au four","it":"Maggi filetto al forno"},
  "images/tiles/items/61-makebreak.jpg": {"de":"Makebreak","en":"Makebreak","es":"Makebreak","fr":"Makebreak","it":"Makebreak"},
  "images/tiles/items/62-oelkanister.jpg": {"de":"Ölkanister","en":"Oil Can","es":"Bidón de aceite","fr":"Bidon d'huile","it":"Tanica d'olio"},
  "images/tiles/items/63-partitur.jpg": {"de":"Partitur","en":"Musical Score","es":"Partitura","fr":"Partition","it":"Partitura"},
  "images/tiles/items/65-rabanus-bier.jpg": {"de":"Rabanus Bier","en":"Rabanus Beer","es":"Cerveza Rabanus","fr":"Bière Rabanus","it":"Birra Rabanus"},
  "images/tiles/items/69-ventslots.jpg": {"de":"Ventslots","en":"Ventslots","es":"Ventslots","fr":"Ventslots","it":"Ventslots"},
  "images/tiles/items/70-wasserfilter.jpg": {"de":"Wasserfilter","en":"Water Filter","es":"Filtro de agua","fr":"Filtre à eau","it":"Filtro dell'acqua"},
  "images/tiles/items/71-wasserwerke.jpg": {"de":"Wasserwerke","en":"Waterworks","es":"Central de aguas","fr":"Usine des eaux","it":"Acquedotto"},
  "images/tiles/items/74-wick-salbei-pack.jpg": {"de":"Wick Salbei Pack","en":"Wick Sage Pack","es":"Wick pack de salvia","fr":"Wick pack sauge","it":"Wick confezione salvia"},
  "images/tiles/items/51-barrier-pflaster.jpg": {"de":"Barrier Pflaster","en":"Barrier Plaster","es":"Apósito Barrier","fr":"Pansement Barrier","it":"Cerotto Barrier"},
  "images/tiles/items/52-blattameise.jpg": {"de":"Blattameise","en":"Leafcutter Ant","es":"Hormiga cortadora de hojas","fr":"Fourmi coupe-feuilles","it":"Formica tagliafoglie"},
  "images/tiles/items/53-crystal.jpg": {"de":"Crystal","en":"Crystal","es":"Cristal","fr":"Cristal","it":"Cristallo"},
  "images/tiles/items/55-easyfix-crinx.jpg": {"de":"Easyfix Crinx","en":"Easyfix Crinx","es":"Easyfix Crinx","fr":"Easyfix Crinx","it":"Easyfix Crinx"},
  "images/tiles/items/58-golden-shoe.jpg": {"de":"Golden Shö","en":"Golden Shö","es":"Golden Shö","fr":"Golden Shö","it":"Golden Shö"},
  "images/tiles/items/59-molekuele2-1.jpg": {"de":"Moleküle2 1","en":"Molecules 2 1","es":"Moléculas 2 1","fr":"Molécules 2 1","it":"Molecole 2 1"},
  "images/tiles/items/64-pencil-knot.jpg": {"de":"Pencil Knot","en":"Pencil Knot","es":"Nudo de lápiz","fr":"Nœud de crayon","it":"Nodo di matita"},
  "images/tiles/items/66-schneiddeckel.jpg": {"de":"Schneiddeckel","en":"Cutting Lid","es":"Tapa cortante","fr":"Couvercle coupant","it":"Coperchio tagliente"},
  "images/tiles/items/67-telefonieren-und-surfen.jpg": {"de":"Telefonieren Und Surfen","en":"Calling and Surfing","es":"Llamar y navegar","fr":"Téléphoner et surfer","it":"Telefonare e navigare"},
  "images/tiles/items/68-edelstahl-ultra.jpg": {"de":"Edelstahl Ultra","en":"Stainless Steel Ultra","es":"Acero inoxidable Ultra","fr":"Acier inoxydable Ultra","it":"Acciaio inox Ultra"},
  "images/tiles/items/72-weihnachtskarte-frankfurt.jpg": {"de":"Weihnachtskarte Frankfurt","en":"Christmas Card Frankfurt","es":"Tarjeta navideña Fráncfort","fr":"Carte de Noël Francfort","it":"Biglietto di Natale Francoforte"},
  "images/tiles/items/73-weihnachtskarte-lb.jpg": {"de":"Weihnachtskarte Lb","en":"Christmas Card LB","es":"Tarjeta navideña LB","fr":"Carte de Noël LB","it":"Biglietto di Natale LB"},
  "images/tiles/items/74-zahnbehandlung.jpg": {"de":"Zahnbehandlung","en":"Dental Treatment","es":"Tratamiento dental","fr":"Soin dentaire","it":"Trattamento dentale"},
  "images/tiles/poster/51-akrinor-oral.jpg": {"de":"Akrinor Oral","en":"Akrinor Oral","es":"Akrinor Oral","fr":"Akrinor Oral","it":"Akrinor Oral"},
  "images/tiles/poster/52-alte-oper.jpg": {"de":"Alte Oper","en":"Alte Oper","es":"Alte Oper","fr":"Alte Oper","it":"Alte Oper"},
  "images/tiles/poster/56-hakle-london.jpg": {"de":"Hakle London","en":"Hakle London","es":"Hakle London","fr":"Hakle London","it":"Hakle London"},
  "images/tiles/poster/57-harry-keaton-poster.jpg": {"de":"Harry Keaton Poster","en":"Harry Keaton Poster","es":"Cartel Harry Keaton","fr":"Affiche Harry Keaton","it":"Manifesto Harry Keaton"},
  "images/tiles/poster/58-scorpions-cover.jpg": {"de":"Scorpions Cover","en":"Scorpions Cover","es":"Portada Scorpions","fr":"Pochette Scorpions","it":"Copertina Scorpions"},
  "images/tiles/poster/61-kinder-advent.jpg": {"de":"Kinder Advent","en":"Kinder Advent","es":"Kinder Advent","fr":"Kinder Advent","it":"Kinder Advent"},
  "images/tiles/poster/64-neuselters.jpg": {"de":"Neuselters","en":"Neuselters","es":"Neuselters","fr":"Neuselters","it":"Neuselters"},
  "images/tiles/poster/66-oral-b.jpg": {"de":"Oral B","en":"Oral B","es":"Oral B","fr":"Oral B","it":"Oral B"},
  "images/tiles/poster/70-schwanensee.jpg": {"de":"Schwanensee","en":"Swan Lake","es":"El lago de los cisnes","fr":"Le Lac des cygnes","it":"Il lago dei cigni"},
  "images/tiles/poster/71-shell-formel1.jpg": {"de":"Shell Formel1","en":"Shell Formula 1","es":"Shell Fórmula 1","fr":"Shell Formule 1","it":"Shell Formula 1"},
  "images/tiles/poster/73-wurlitzer.jpg": {"de":"Wurlitzer","en":"Wurlitzer","es":"Wurlitzer","fr":"Wurlitzer","it":"Wurlitzer"},
  "images/tiles/poster/74-pioneer-hifi.jpg": {"de":"Pioneer Hifi","en":"Pioneer Hi-Fi","es":"Pioneer Hi-Fi","fr":"Pioneer Hi-Fi","it":"Pioneer Hi-Fi"},
  "images/tiles/poster/50-adventskalender.jpg": {"de":"Adventskalender","en":"Advent Calendar","es":"Calendario de adviento","fr":"Calendrier de l'Avent","it":"Calendario dell'Avvento"},
  "images/tiles/poster/53-batida-plakat.jpg": {"de":"Batida Plakat","en":"Batida Poster","es":"Cartel Batida","fr":"Affiche Batida","it":"Manifesto Batida"},
  "images/tiles/poster/54-douwe-egberts.jpg": {"de":"Douwe Egberts","en":"Douwe Egberts","es":"Douwe Egberts","fr":"Douwe Egberts","it":"Douwe Egberts"},
  "images/tiles/poster/55-floradix.jpg": {"de":"Floradix","en":"Floradix","es":"Floradix","fr":"Floradix","it":"Floradix"},
  "images/tiles/poster/58-huegli-titel.jpg": {"de":"Hügli Titel","en":"Hügli Cover","es":"Portada Hügli","fr":"Couverture Hügli","it":"Copertina Hügli"},
  "images/tiles/poster/59-kinder-snoopy.jpg": {"de":"Kinder Snoopy","en":"Kinder Snoopy","es":"Kinder Snoopy","fr":"Kinder Snoopy","it":"Kinder Snoopy"},
  "images/tiles/poster/60-kleenex.jpg": {"de":"Kleenex","en":"Kleenex","es":"Kleenex","fr":"Kleenex","it":"Kleenex"},
  "images/tiles/poster/62-marlboro-moskau.jpg": {"de":"Marlboro Moskau","en":"Marlboro Moscow","es":"Marlboro Moscú","fr":"Marlboro Moscou","it":"Marlboro Mosca"},
  "images/tiles/poster/63-shell-lenkdrachen.jpg": {"de":"Shell Lenkdrachen","en":"Shell Stunt Kite","es":"Shell cometa acrobática","fr":"Shell cerf-volant acrobatique","it":"Shell aquilone acrobatico"},
  "images/tiles/poster/65-new-york.jpg": {"de":"New York","en":"New York","es":"Nueva York","fr":"New York","it":"New York"},
  "images/tiles/poster/67-picanto-poster.jpg": {"de":"Picanto Poster","en":"Picanto Poster","es":"Cartel Picanto","fr":"Affiche Picanto","it":"Manifesto Picanto"},
  "images/tiles/poster/68-geniessen.jpg": {"de":"Geniessen","en":"Enjoy","es":"Disfrutar","fr":"Savourer","it":"Gustare"},
  "images/tiles/poster/69-meckmotors-logo.jpg": {"de":"Meckmotors Logo","en":"Meckmotors Logo","es":"Logotipo Meckmotors","fr":"Logo Meckmotors","it":"Logo Meckmotors"},
  "images/tiles/poster/72-shell-tankwart.jpg": {"de":"Shell Tankwart","en":"Shell Petrol Attendant","es":"Shell gasolinero","fr":"Shell pompiste","it":"Shell benzinaio"},
  "images/tiles/pharma/51-akrinor2.jpg": {"de":"Akrinor2","en":"Akrinor 2","es":"Akrinor 2","fr":"Akrinor 2","it":"Akrinor 2"},
  "images/tiles/pharma/53-alzheimer.jpg": {"de":"Alzheimer","en":"Alzheimer's","es":"Alzhéimer","fr":"Alzheimer","it":"Alzheimer"},
  "images/tiles/pharma/55-blutgerinnung.jpg": {"de":"Blutgerinnung","en":"Blood Coagulation","es":"Coagulación sanguínea","fr":"Coagulation sanguine","it":"Coagulazione del sangue"},
  "images/tiles/pharma/56-capillary-leak.jpg": {"de":"Capillary Leak","en":"Capillary Leak","es":"Fuga capilar","fr":"Fuite capillaire","it":"Perdita capillare"},
  "images/tiles/pharma/58-easyfix-crinx.jpg": {"de":"Easyfix Crinx","en":"Easyfix Crinx","es":"Easyfix Crinx","fr":"Easyfix Crinx","it":"Easyfix Crinx"},
  "images/tiles/pharma/60-foetus.jpg": {"de":"Fötus","en":"Foetus","es":"Feto","fr":"Fœtus","it":"Feto"},
  "images/tiles/pharma/61-hirnblutung.jpg": {"de":"Hirnblutung","en":"Cerebral Haemorrhage","es":"Hemorragia cerebral","fr":"Hémorragie cérébrale","it":"Emorragia cerebrale"},
  "images/tiles/pharma/64-molekuel.jpg": {"de":"Molekül","en":"Molecule","es":"Molécula","fr":"Molécule","it":"Molecola"},
  "images/tiles/pharma/65-mundspuelung.jpg": {"de":"Mundspülung","en":"Mouthwash","es":"Enjuague bucal","fr":"Bain de bouche","it":"Collutorio"},
  "images/tiles/pharma/66-sklerose.jpg": {"de":"Sklerose","en":"Sclerosis","es":"Esclerosis","fr":"Sclérose","it":"Sclerosi"},
  "images/tiles/pharma/50-akrinor1.jpg": {"de":"Akrinor1","en":"Akrinor 1","es":"Akrinor 1","fr":"Akrinor 1","it":"Akrinor 1"},
  "images/tiles/pharma/52-akrinor3.jpg": {"de":"Akrinor3","en":"Akrinor 3","es":"Akrinor 3","fr":"Akrinor 3","it":"Akrinor 3"},
  "images/tiles/pharma/54-biofilm.jpg": {"de":"Biofilm","en":"Biofilm","es":"Biopelícula","fr":"Biofilm","it":"Biofilm"},
  "images/tiles/pharma/57-coverplast.jpg": {"de":"Coverplast","en":"Coverplast","es":"Coverplast","fr":"Coverplast","it":"Coverplast"},
  "images/tiles/pharma/59-elastoplast.jpg": {"de":"Elastoplast","en":"Elastoplast","es":"Elastoplast","fr":"Elastoplast","it":"Elastoplast"},
  "images/tiles/pharma/62-lymhsystem.jpg": {"de":"Lymhsystem","en":"Lymphatic System","es":"Sistema linfático","fr":"Système lymphatique","it":"Sistema linfatico"},
  "images/tiles/pharma/63-lymphsystem-legs.jpg": {"de":"Lymphsystem Legs","en":"Lymphatic System Legs","es":"Sistema linfático piernas","fr":"Système lymphatique jambes","it":"Sistema linfatico gambe"},
  "images/tiles/pharma/67-thrombus.jpg": {"de":"Thrombus","en":"Thrombus","es":"Trombo","fr":"Thrombus","it":"Trombo"},
  "images/tiles/pharma/68-tumor-grenzregion.jpg": {"de":"Tumor Grenzregion","en":"Tumour Border Region","es":"Región limítrofe del tumor","fr":"Région frontière de la tumeur","it":"Regione di confine del tumore"},
  "images/tiles/pharma/69-uteral-bleeding.jpg": {"de":"Uteral Bleeding","en":"Uterine Bleeding","es":"Sangrado uterino","fr":"Saignement utérin","it":"Sanguinamento uterino"},
  "images/tiles/logos/50-ali-baba.jpg": {"de":"Ali Baba","en":"Ali Baba","es":"Ali Baba","fr":"Ali Baba","it":"Ali Baba"},
  "images/tiles/logos/54-bizzl-logo.jpg": {"de":"Bizzl Logo","en":"Bizzl Logo","es":"Logotipo Bizzl","fr":"Logo Bizzl","it":"Logo Bizzl"},
  "images/tiles/logos/55-celtica.jpg": {"de":"Celtica","en":"Celtica","es":"Celtica","fr":"Celtica","it":"Celtica"},
  "images/tiles/logos/59-indigo.jpg": {"de":"Indigo","en":"Indigo","es":"Índigo","fr":"Indigo","it":"Indaco"},
  "images/tiles/logos/61-leaf-cup.jpg": {"de":"Leaf Cup","en":"Leaf Cup","es":"Leaf Cup","fr":"Leaf Cup","it":"Leaf Cup"},
  "images/tiles/logos/63-moguntia.jpg": {"de":"Moguntia","en":"Moguntia","es":"Moguntia","fr":"Moguntia","it":"Moguntia"},
  "images/tiles/logos/66-neon-sign.jpg": {"de":"Neon Sign","en":"Neon Sign","es":"Letrero de neón","fr":"Enseigne néon","it":"Insegna al neon"},
  "images/tiles/logos/67-paper-creation.jpg": {"de":"Paper Creation","en":"Paper Creation","es":"Creación en papel","fr":"Création papier","it":"Creazione di carta"},
  "images/tiles/logos/69-sciencex.jpg": {"de":"Sciencex","en":"Sciencex","es":"Sciencex","fr":"Sciencex","it":"Sciencex"},
  "images/tiles/logos/72-xxl.jpg": {"de":"Xxl","en":"XXL","es":"XXL","fr":"XXL","it":"XXL"},
  "images/tiles/logos/73-xylit.jpg": {"de":"Xylit","en":"Xylitol","es":"Xilitol","fr":"Xylitol","it":"Xilitolo"},
  "images/tiles/logos/51-art-of-fantasy.jpg": {"de":"Art Of Fantasy","en":"Art of Fantasy","es":"Arte de fantasía","fr":"Art de la fantaisie","it":"Arte della fantasia"},
  "images/tiles/logos/52-baders.jpg": {"de":"Baders","en":"Baders","es":"Baders","fr":"Baders","it":"Baders"},
  "images/tiles/logos/53-bidcar24.jpg": {"de":"Bidcar24","en":"Bidcar24","es":"Bidcar24","fr":"Bidcar24","it":"Bidcar24"},
  "images/tiles/logos/56-css-logo.jpg": {"de":"Cß Logo","en":"Cß Logo","es":"Logotipo Cß","fr":"Logo Cß","it":"Logo Cß"},
  "images/tiles/logos/56-meckmotors-vintage.jpg": {"de":"Meckmotors Vintage","en":"Meckmotors Vintage","es":"Meckmotors Vintage","fr":"Meckmotors Vintage","it":"Meckmotors Vintage"},
  "images/tiles/logos/57-frankfurt-film.jpg": {"de":"Frankfurt Film","en":"Frankfurt Film","es":"Película Fráncfort","fr":"Film Francfort","it":"Film Francoforte"},
  "images/tiles/logos/58-grafilino.jpg": {"de":"Grafilino","en":"Grafilino","es":"Grafilino","fr":"Grafilino","it":"Grafilino"},
  "images/tiles/logos/60-joy-logo.jpg": {"de":"Joy Logo","en":"Joy Logo","es":"Logotipo Joy","fr":"Logo Joy","it":"Logo Joy"},
  "images/tiles/logos/62-mexica.jpg": {"de":"Mexica","en":"Mexica","es":"Mexica","fr":"Mexica","it":"Mexica"},
  "images/tiles/logos/64-name-der-rose.jpg": {"de":"Name Der Rose","en":"The Name of the Rose","es":"El nombre de la rosa","fr":"Le Nom de la rose","it":"Il nome della rosa"},
  "images/tiles/logos/65-nebelhorn-logo.jpg": {"de":"Nebelhorn Logo","en":"Nebelhorn Logo","es":"Logotipo Nebelhorn","fr":"Logo Nebelhorn","it":"Logo Nebelhorn"},
  "images/tiles/logos/68-bake-create.jpg": {"de":"Bake Create","en":"Bake Create","es":"Bake Create","fr":"Bake Create","it":"Bake Create"},
  "images/tiles/logos/68-saucenmedallie.jpg": {"de":"Saucenmedallie","en":"Sauce Medal","es":"Medalla de salsa","fr":"Médaille de sauce","it":"Medaglia della salsa"},
  "images/tiles/logos/70-spardoch.jpg": {"de":"Spardoch","en":"Spardoch","es":"Spardoch","fr":"Spardoch","it":"Spardoch"},
  "images/tiles/logos/71-timesquare.jpg": {"de":"Timesquare","en":"Times Square","es":"Times Square","fr":"Times Square","it":"Times Square"},
  "images/tiles/logos/74-zeitperlen.jpg": {"de":"Zeitperlen","en":"Time Pearls","es":"Perlas del tiempo","fr":"Perles du temps","it":"Perle del tempo"},
  "images/tiles/packaging/50-big-kini.jpg": {"de":"Big Kini","en":"Big Kini","es":"Big Kini","fr":"Big Kini","it":"Big Kini"},
  "images/tiles/packaging/51-bluff.jpg": {"de":"Bluff","en":"Bluff","es":"Bluff","fr":"Bluff","it":"Bluff"},
  "images/tiles/packaging/52-buddel-company.jpg": {"de":"Buddel Company","en":"Buddel Company","es":"Buddel Company","fr":"Buddel Company","it":"Buddel Company"},
  "images/tiles/packaging/57-himbeergeist.jpg": {"de":"Himbeergeist","en":"Raspberry Brandy","es":"Aguardiente de frambuesa","fr":"Eau-de-vie de framboise","it":"Acquavite di lampone"},
  "images/tiles/packaging/62-leaf-cup.jpg": {"de":"Leaf Cup","en":"Leaf Cup","es":"Leaf Cup","fr":"Leaf Cup","it":"Leaf Cup"},
  "images/tiles/packaging/66-mon-cheri-ei.jpg": {"de":"Mon Cheri Ei","en":"Mon Cheri Egg","es":"Mon Cheri huevo","fr":"Mon Cheri œuf","it":"Mon Cheri uovo"},
  "images/tiles/packaging/67-mon-cheri-fruehling.jpg": {"de":"Mon Cheri Frühling","en":"Mon Cheri Spring","es":"Mon Cheri primavera","fr":"Mon Cheri printemps","it":"Mon Cheri primavera"},
  "images/tiles/packaging/68-multivitamin.jpg": {"de":"Multivitamin","en":"Multivitamin","es":"Multivitamínico","fr":"Multivitamines","it":"Multivitaminico"},
  "images/tiles/packaging/69-piraten.jpg": {"de":"Piraten","en":"Pirates","es":"Piratas","fr":"Pirates","it":"Pirati"},
  "images/tiles/packaging/71-royal-casino.jpg": {"de":"Royal Casino","en":"Royal Casino","es":"Royal Casino","fr":"Royal Casino","it":"Royal Casino"},
  "images/tiles/packaging/72-teastar-display.jpg": {"de":"Teastar Display","en":"Teastar Display","es":"Expositor Teastar","fr":"Présentoir Teastar","it":"Espositore Teastar"},
  "images/tiles/packaging/73-tops.jpg": {"de":"Tops","en":"Tops","es":"Tops","fr":"Tops","it":"Tops"},
  "images/tiles/packaging/74-zaubershow.jpg": {"de":"Zaubershow","en":"Magic Show","es":"Espectáculo de magia","fr":"Spectacle de magie","it":"Spettacolo di magia"},
  "images/tiles/packaging/53-display-teastar.jpg": {"de":"Display Teastar","en":"Teastar Display","es":"Expositor Teastar","fr":"Présentoir Teastar","it":"Espositore Teastar"},
  "images/tiles/packaging/54-energietaler.jpg": {"de":"Energietaler","en":"Energy Taler","es":"Tálero de energía","fr":"Thaler d'énergie","it":"Tallero dell'energia"},
  "images/tiles/packaging/55-froeschle-tiernahrung.jpg": {"de":"Fröschle Tiernahrung","en":"Fröschle Pet Food","es":"Fröschle alimento para mascotas","fr":"Fröschle nourriture pour animaux","it":"Fröschle alimenti per animali"},
  "images/tiles/packaging/56-gedaechtnistee.jpg": {"de":"Gedächtnistee","en":"Memory Tea","es":"Té de la memoria","fr":"Thé de la mémoire","it":"Tè della memoria"},
  "images/tiles/packaging/58-huegli-gourmet.jpg": {"de":"Hügli Gourmet","en":"Hügli Gourmet","es":"Hügli Gourmet","fr":"Hügli Gourmet","it":"Hügli Gourmet"},
  "images/tiles/packaging/59-joy-dosen.jpg": {"de":"Joy Dosen","en":"Joy Cans","es":"Latas Joy","fr":"Boîtes Joy","it":"Lattine Joy"},
  "images/tiles/packaging/60-joy-display.jpg": {"de":"Joy Display","en":"Joy Display","es":"Expositor Joy","fr":"Présentoir Joy","it":"Espositore Joy"},
  "images/tiles/packaging/61-konfituere.jpg": {"de":"Konfitüre","en":"Jam","es":"Confitura","fr":"Confiture","it":"Confettura"},
  "images/tiles/packaging/63-lemon.jpg": {"de":"Lemon","en":"Lemon","es":"Limón","fr":"Citron","it":"Limone"},
  "images/tiles/packaging/64-lindt-geschenkpackung.jpg": {"de":"Lindt Geschenkpackung","en":"Lindt Gift Pack","es":"Lindt estuche de regalo","fr":"Lindt coffret cadeau","it":"Lindt confezione regalo"},
  "images/tiles/packaging/65-maggi-benedict.jpg": {"de":"Maggi Benedict","en":"Maggi Benedict","es":"Maggi Benedict","fr":"Maggi Benedict","it":"Maggi Benedict"},
  "images/tiles/packaging/70-premium-tea.jpg": {"de":"Premium Tea","en":"Premium Tea","es":"Té premium","fr":"Thé premium","it":"Tè premium"},
};
const DESCRIPTIONS = {
};
const VARIANTS = {
  "images/tiles/food/51-schokokirsche.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/52-kaffee-milch.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/60-dimple-drink-art.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/63-fine-dining.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/65-liptonice.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/66-mezzomix.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/68-nutella-fussball.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/70-sarotti-likoer-splash.jpg": {"w":[400,800],"large":true},
  "images/tiles/food/71-schokolikoer.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/73-tomaten.jpg": {"w":[400,800],"large":true},
  "images/tiles/food/50-pflaume-feige.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/53-orangenmarmelade.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/54-creme-de-balsamico.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/55-drinks-exotisch.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/56-lime-coffee.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/57-bebivita-schoko.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/58-birne-apfel.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/59-caffreddo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/61-eiscafe.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/62-fertiggerichte.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/64-halloren-waldfrucht.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/67-milchkaffee.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/69-oranges.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/72-tegut-muesliriegel.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/food/74-valbrie.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/50-red-racer.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/52-pink-cadillac.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/53-db-ice.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/54-dreamcar.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/55-ferrari-f-50.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/56-easyriders.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/61-motorace.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/63-easifixk.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/66-vedder-bootsausstattung.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/51-alvis-roadster.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/58-alfa-romeo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/59-monster-trucks.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/60-moto-cross.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/62-verkehrswege.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/64-wassertest.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/65-starck-wc.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/67-vedder-systemtisch.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/68-buffer-anlage.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/transport/69-manz-robot.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/50-airstream.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/51-almette.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/52-alte-oper-plakat.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/53-cant-stop.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/54-cutty-sark.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/57-faszination-fussball.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/59-gas-station.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/64-maggi-toscana.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/66-pharaonengrab.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/68-segelregatta.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/71-underwater.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/72-vodafone-zuhause.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/74-worldgate.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/55-delphine-mit-truhe.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/56-energie-landschaften.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/58-ferrero-pasticceria.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/60-haus-innen-neu.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/61-fussball-kulinarisch.jpg": {"w":[400,800],"large":true},
  "images/tiles/landscape/62-hollandrad.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/63-kuba.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/65-maerchenschloss.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/67-plantage.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/69-sonnensystem.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/70-suedsee.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/landscape/73-weideglueck.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/50-bosch-halogen.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/52-konditor-bildmarke.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/53-lippenstift.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/54-hula-hoop-girl.jpg": {"w":[400,800],"large":true},
  "images/tiles/people/55-foetus.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/57-kleenex.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/59-rene-garraud.jpg": {"w":[400,800],"large":true},
  "images/tiles/people/62-joker.jpg": {"w":[400,800],"large":true},
  "images/tiles/people/64-schweinischer-engel.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/66-hr3-hoerminator.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/68-drachentoeter.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/51-cavallino-rampante.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/56-kaesemeister.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/58-lollypop-mann.jpg": {"w":[400,800],"large":true},
  "images/tiles/people/60-weihnachtsschokolade.jpg": {"w":[400,800],"large":true},
  "images/tiles/people/61-maggi-diavolo.jpg": {"w":[400,800],"large":true},
  "images/tiles/people/63-comic-motive.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/65-wassermusik.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/67-tyrannosaurus-rex.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/people/69-hunde.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/50-bad-liebenzeller.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/54-cutimed-produkte.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/56-edelstahl.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/57-glaskopf.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/59-honigmilch.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/60-maggi-ofen-filet.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/61-makebreak.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/62-oelkanister.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/63-partitur.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/65-rabanus-bier.jpg": {"w":[400,800],"large":true},
  "images/tiles/items/69-ventslots.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/70-wasserfilter.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/71-wasserwerke.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/74-wick-salbei-pack.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/51-barrier-pflaster.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/52-blattameise.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/53-crystal.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/55-easyfix-crinx.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/58-golden-shoe.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/59-molekuele2-1.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/64-pencil-knot.jpg": {"w":[400,800],"large":true},
  "images/tiles/items/66-schneiddeckel.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/67-telefonieren-und-surfen.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/68-edelstahl-ultra.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/72-weihnachtskarte-frankfurt.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/73-weihnachtskarte-lb.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/items/74-zahnbehandlung.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/51-akrinor-oral.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/52-alte-oper.jpg": {"w":[400,800],"large":true},
  "images/tiles/poster/56-hakle-london.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/57-harry-keaton-poster.jpg": {"w":[400,800],"large":true},
  "images/tiles/poster/58-scorpions-cover.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/61-kinder-advent.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/64-neuselters.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/66-oral-b.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/70-schwanensee.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/71-shell-formel1.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/73-wurlitzer.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/74-pioneer-hifi.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/50-adventskalender.jpg": {"w":[400,800],"large":true},
  "images/tiles/poster/53-batida-plakat.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/54-douwe-egberts.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/55-floradix.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/58-huegli-titel.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/59-kinder-snoopy.jpg": {"w":[400,800],"large":true},
  "images/tiles/poster/60-kleenex.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/62-marlboro-moskau.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/63-shell-lenkdrachen.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/65-new-york.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/67-picanto-poster.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/68-geniessen.jpg": {"w":[400,800],"large":true},
  "images/tiles/poster/69-meckmotors-logo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/poster/72-shell-tankwart.jpg": {"w":[400,800],"large":true},
  "images/tiles/pharma/51-akrinor2.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/53-alzheimer.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/55-blutgerinnung.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/56-capillary-leak.jpg": {"w":[400,800],"large":true},
  "images/tiles/pharma/58-easyfix-crinx.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/60-foetus.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/61-hirnblutung.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/64-molekuel.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/65-mundspuelung.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/66-sklerose.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/50-akrinor1.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/52-akrinor3.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/54-biofilm.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/57-coverplast.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/59-elastoplast.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/62-lymhsystem.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/63-lymphsystem-legs.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/67-thrombus.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/68-tumor-grenzregion.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/pharma/69-uteral-bleeding.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/50-ali-baba.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/54-bizzl-logo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/55-celtica.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/59-indigo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/61-leaf-cup.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/63-moguntia.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/66-neon-sign.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/67-paper-creation.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/69-sciencex.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/72-xxl.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/73-xylit.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/51-art-of-fantasy.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/52-baders.jpg": {"w":[400,800],"large":true},
  "images/tiles/logos/53-bidcar24.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/56-css-logo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/56-meckmotors-vintage.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/57-frankfurt-film.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/58-grafilino.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/60-joy-logo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/62-mexica.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/64-name-der-rose.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/65-nebelhorn-logo.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/68-bake-create.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/68-saucenmedallie.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/70-spardoch.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/71-timesquare.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/logos/74-zeitperlen.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/50-big-kini.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/51-bluff.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/52-buddel-company.jpg": {"w":[400,800],"large":true},
  "images/tiles/packaging/57-himbeergeist.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/62-leaf-cup.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/66-mon-cheri-ei.jpg": {"w":[400,800],"large":true},
  "images/tiles/packaging/67-mon-cheri-fruehling.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/68-multivitamin.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/69-piraten.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/71-royal-casino.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/72-teastar-display.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/73-tops.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/74-zaubershow.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/53-display-teastar.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/54-energietaler.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/55-froeschle-tiernahrung.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/56-gedaechtnistee.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/58-huegli-gourmet.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/59-joy-dosen.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/60-joy-display.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/61-konfituere.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/63-lemon.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/64-lindt-geschenkpackung.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/65-maggi-benedict.jpg": {"w":[400,800,1200],"large":true},
  "images/tiles/packaging/70-premium-tea.jpg": {"w":[400,800,1200],"large":true},
};
